image: node:12.21.0

build:
  stage: build
  before_script:
    - apt update -y && apt install zip -y
  script:
    - yarn
    - yarn build
    - (cd build && zip -r ../application.zip .)
    - echo '{"version":1,"manifestURL":"https://affenull2345.gitlab.io/store-client/manifest.webapp"}' > metadata.json
    - zip store.zip metadata.json application.zip
  artifacts:
    paths:
      - store.zip
      - build

pages:
  stage: deploy
  script:
    - mv public _public
    - mkdir public
    - cp store.zip build/manifest.webapp public/
  artifacts:
    paths:
      - public
  only:
    - tags
